"""empty message

Revision ID: bd837acb8edf
Revises: c2aab5e272be
Create Date: 2024-03-17 17:44:40.197445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd837acb8edf'
down_revision: Union[str, None] = 'c2aab5e272be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pastes', 'expiration',
               existing_type=sa.VARCHAR(),
               type_=sa.Interval(),
               existing_nullable=True,
               postgresql_using='expiration::interval')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pastes', 'expiration',
               existing_type=sa.Interval(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
